import { build } from "esbuild"
import { mkdir, writeFile } from "node:fs/promises"
const result = await build({
  entryPoints: ["maplibre-gl/dist/maplibre-gl-worker.mjs"],
  bundle: true, write: false, minify: true, format: "iife", platform: "browser", target: "es2022", legalComments: "inline",
})
await mkdir("src/generated", { recursive: true })
await writeFile("src/generated/maplibre-worker.ts", `// Generated by scripts/prepare-worker.mjs; do not edit.\nexport default ${JSON.stringify(result.outputFiles[0].text)}\n`)
